version: '3.8'

  services:
    app:
      build: .
      container_name: currency-converter-api
      ports:
        - "3000:3000"
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_DB=0
        - CACHE_TTL=300
        - NODE_ENV=production
      depends_on:
        - redis
      networks:
        - currency-network

    redis:
      image: redis:7-alpine
      container_name: currency-converter-redis
      ports:
        - "6379:6379"
      command: redis-server --appendonly yes
      volumes:
        - redis_data:/data
      networks:
        - currency-network

  volumes:
    redis_data:

  networks:
    currency-network: